import { test, expect, username, password } from '../fixtures';
import { LoginPage, RegisterPage, ResetPasswordPage } from '../pages/auth.page';
import { ShellPage } from '../pages/shell.page';
import { AdminPage } from '../pages/admin.page';
import { DocumentPage } from '../pages/document.page';
import { ListsPage } from '../pages/lists.page';

test('[E2E] TEST-004 TEST-005 TEST-010 TEST-013 TEST-044: protege rutas, bloquea registro sin invitacion y rechaza reset inexistente (variantes reales)', async ({ page, request }) => {
  const login = new LoginPage(page);
  const register = new RegisterPage(page);
  const reset = new ResetPasswordPage(page);
  const shell = new ShellPage(page);
  const document = new DocumentPage(page);
  for (const path of ['/', '/desconocida', '/listas', '/amigos', '/admin']) {
    await shell.goto(path);
    await expect(page).toHaveURL('/login');
    await expect(login.pageHeading).toBeVisible();
  }
  await expect(page).toHaveTitle('EntreRegalos');
  await expect(document.html).toHaveAttribute('lang', 'es');
  await login.submit();
  expect(await login.usernameInput.evaluate((input: HTMLInputElement) => input.validity.valueMissing)).toBe(true);
  await login.registerLink.click();
  await expect(register.invitationRequired).toBeVisible();
  await expect(register.submitButton).toBeDisabled();
  expect((await request.post('/api/v1/auth/register', { data: { username: username(), password } })).status()).toBe(400);
  await reset.goto();
  await expect(reset.missingTokenMessage).toBeVisible();
  const invalidReset = page.waitForResponse((response) =>
    new URL(response.url()).pathname === '/api/v1/auth/reset-password/validate');
  await reset.goto('00000000-0000-4000-8000-000000000000');
  expect((await invalidReset).status()).toBe(410);
  await expect(reset.invalidTokenMessage).toBeVisible();
  expect((await request.get('/api/v1/lists')).status()).toBe(401);
  expect((await request.get('/api/v1/users')).status()).toBe(401);
});

test('[E2E] TEST-007 TEST-008 TEST-009 TEST-017: login, error string, refresh y logout reales impiden reutilizar refresh', async ({ page, context, account, request }) => {
  const login = new LoginPage(page);
  const shell = new ShellPage(page);
  const lists = new ListsPage(page);
  await login.goto();
  await login.fillCredentials(account.username, 'wrong-password');
  await login.submit();
  await expect(login.error('Credenciales incorrectas')).toBeVisible();
  await expect(page).toHaveURL('/login');
  await login.fillCredentials(account.username, account.password);
  await login.submit();
  await expect(page).toHaveURL('/listas');
  await expect(lists.heading).toBeVisible();
  await page.reload();
  await expect(shell.username(account.username)).toBeVisible();
  const cookies = (await context.cookies()).filter((cookie) => cookie.name === 'refreshToken');
  expect(cookies).toHaveLength(1);
  expect(cookies[0]).toMatchObject({ httpOnly: true, sameSite: 'Strict', path: '/api/v1/auth' });
  const refreshed = await page.evaluate(async () => {
    const response = await fetch('/api/v1/auth/refresh', { method: 'POST', credentials: 'include' });
    return { status: response.status, body: await response.json() };
  });
  expect(refreshed.status).toBe(200);
  const me = await request.get('/api/v1/auth/me', { headers: { Authorization: `Bearer ${refreshed.body.accessToken}` } });
  expect(me.status()).toBe(200);
  expect(await me.json()).toMatchObject({ id: account.id, username: account.username });
  const loggedOut = page.waitForResponse((response) => new URL(response.url()).pathname === '/api/v1/auth/logout');
  await shell.logoutButton.click();
  expect((await loggedOut).status()).toBe(200);
  await expect(page).toHaveURL('/login');
  expect(await page.evaluate(() => localStorage.getItem('accessToken'))).toBeNull();
  expect((await context.cookies()).filter((cookie) => cookie.name === 'refreshToken')).toEqual([]);
  expect(await page.evaluate(async () => (await fetch('/api/v1/auth/refresh', { method: 'POST', credentials: 'include' })).status)).toBe(401);
  const replay = await request.post('/api/v1/auth/refresh', { headers: { Cookie: `refreshToken=${cookies[0].value}` } });
  expect(replay.status()).toBe(401);
  await shell.goto('/listas');
  await expect(page).toHaveURL('/login');
});

test('[E2E] TEST-006 TEST-037: restringe administracion y persiste desactivacion y reactivacion reales', async ({ page, account, admin, createAccount }) => {
  const login = new LoginPage(page);
  const shell = new ShellPage(page);
  const lists = new ListsPage(page);
  const adminPage = new AdminPage(page);
  const target = await createAccount();
  await login.goto();
  await login.fillCredentials(account.username, account.password);
  await login.submit();
  await expect(page).toHaveURL('/listas');
  await expect(lists.heading).toBeVisible();
  await expect(shell.adminLink).toHaveCount(0);
  await shell.goto('/admin');
  await expect(page).toHaveURL('/listas');
  expect((await account.api.get('/api/v1/invitations')).status()).toBe(403);
  expect((await account.api.post('/api/v1/invitations', { data: {} })).status()).toBe(403);
  expect((await account.api.post(`/api/v1/users/${target.id}/reset-password`)).status()).toBe(403);
  expect((await account.api.patch(`/api/v1/users/${target.id}/deactivate`)).status()).toBe(403);
  await shell.logoutButton.click();
  await expect(page).toHaveURL('/login');
  await login.fillCredentials(admin.username, admin.password);
  await login.submit();
  await expect(page).toHaveURL('/listas');
  await expect(lists.heading).toBeVisible();
  await shell.adminLink.click();
  const self = adminPage.userRow(admin.username);
  await expect(self).toBeVisible();
  await expect(adminPage.deactivateButton(admin.username)).toHaveCount(0);
  const row = adminPage.userRow(account.username);
  await adminPage.deactivateButton(account.username).click();
  await expect(row.getByRole('cell', { name: 'Inactivo', exact: true })).toBeVisible();
  await page.reload();
  await expect(row.getByRole('cell', { name: 'Inactivo', exact: true })).toBeVisible();
  expect((await account.api.get('/api/v1/auth/me')).status()).toBe(401);
  expect((await page.request.post('/api/v1/auth/login', { data: { username: account.username, password: account.password } })).status()).toBe(401);
  await adminPage.activateButton(account.username).click();
  await expect(row.getByRole('cell', { name: 'Activo', exact: true })).toBeVisible();
  await page.reload();
  await expect(row.getByRole('cell', { name: 'Activo', exact: true })).toBeVisible();
  expect((await account.api.get('/api/v1/auth/me')).status()).toBe(200);
  await shell.logoutButton.click();
  await expect(page).toHaveURL('/login');
  await login.fillCredentials(account.username, account.password);
  await login.submit();
  await expect(page).toHaveURL('/listas');
  await expect(lists.heading).toBeVisible();
});
